on:
  push: # Se ejecuta cuando hay un push en el repositorio
    branches:
      - main
  pull_request: # Se ejecuta en los PR a la rama main
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout main branch with github task
      - name: 'Checkout main'
        uses: actions/checkout@main
      # Install doctl
      - name: 'Install doctl'
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # Construir la imagen
      - name: 'Build container image'
        run: docker build -t registry.digitalocean.com/munyaal-docr/munyaal/website:$(echo $GITHUB_SHA | head -c7) .
      # Log In to Registry
      - name: 'Log in to DigitalOcean Container Registry with short-lived credentials'
        run: doctl registry login --expiry-seconds 1200
      # Subir imagen al registry
      - name: 'Push image to DigitalOcean Container Registry'
        run: docker push registry.digitalocean.com/munyaal-docr/munyaal/website:$(echo $GITHUB_SHA | head -c7)
      


     
